# The deployment section should be excluded until
# it is explicitly included in module 5





version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      # - run: pip install -r requirements/dev.txt
test:
  override:
    - mocha
deployment:
 dockerhub:
   branch: master
   commands:
     - $DOCKER_HUB_TRIGGER
