# The deployment section should be excluded until
# it is explicitly included in module 5

#deployment:
#  dockerhub:
#    branch: master
#    commands:
#      - $DOCKER_HUB_TRIGGER

# test:
#   override:
#     - mocha

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/python:3.6.2-stretch-browsers
#     steps:
#       - checkout
#       - run: pip install -r requirements/dev.txt


version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt
  test:
verride:
    - mocha
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
